// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.2
// source: syncaliyunoss.proto

package syncaliyunoss

import (
	context "context"
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AliyunOssRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoint         string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	BucketName       string `protobuf:"bytes,2,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	ObjectNamePrefix string `protobuf:"bytes,3,opt,name=object_name_prefix,json=objectNamePrefix,proto3" json:"object_name_prefix,omitempty"`
	FileName         string `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Md5SumValue      string `protobuf:"bytes,5,opt,name=md5sum_value,json=md5sumValue,proto3" json:"md5sum_value,omitempty"`
	Timestamp        int64  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *AliyunOssRequest) Reset() {
	*x = AliyunOssRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syncaliyunoss_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AliyunOssRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliyunOssRequest) ProtoMessage() {}

func (x *AliyunOssRequest) ProtoReflect() protoreflect.Message {
	mi := &file_syncaliyunoss_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliyunOssRequest.ProtoReflect.Descriptor instead.
func (*AliyunOssRequest) Descriptor() ([]byte, []int) {
	return file_syncaliyunoss_proto_rawDescGZIP(), []int{0}
}

func (x *AliyunOssRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AliyunOssRequest) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *AliyunOssRequest) GetObjectNamePrefix() string {
	if x != nil {
		return x.ObjectNamePrefix
	}
	return ""
}

func (x *AliyunOssRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *AliyunOssRequest) GetMd5SumValue() string {
	if x != nil {
		return x.Md5SumValue
	}
	return ""
}

func (x *AliyunOssRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type AliyunOssReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ErrCode int32  `protobuf:"varint,6,opt,name=errCode,proto3" json:"errCode,omitempty"`
}

func (x *AliyunOssReply) Reset() {
	*x = AliyunOssReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_syncaliyunoss_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AliyunOssReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliyunOssReply) ProtoMessage() {}

func (x *AliyunOssReply) ProtoReflect() protoreflect.Message {
	mi := &file_syncaliyunoss_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliyunOssReply.ProtoReflect.Descriptor instead.
func (*AliyunOssReply) Descriptor() ([]byte, []int) {
	return file_syncaliyunoss_proto_rawDescGZIP(), []int{1}
}

func (x *AliyunOssReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AliyunOssReply) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

var File_syncaliyunoss_proto protoreflect.FileDescriptor

var file_syncaliyunoss_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x79, 0x6e, 0x63, 0x61, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x6f, 0x73, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x73, 0x79, 0x6e, 0x63, 0x61, 0x6c, 0x69, 0x79, 0x75,
	0x6e, 0x6f, 0x73, 0x73, 0x22, 0xdb, 0x01, 0x0a, 0x10, 0x41, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x4f,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b,
	0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x50, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x64, 0x35, 0x73, 0x75, 0x6d, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x64, 0x35, 0x73, 0x75, 0x6d, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x22, 0x44, 0x0a, 0x0e, 0x41, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x4f, 0x73, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x32, 0x64, 0x0a, 0x11, 0x53, 0x79, 0x6e, 0x63,
	0x41, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x4f, 0x73, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x4f, 0x0a,
	0x0b, 0x53, 0x79, 0x6e, 0x63, 0x4f, 0x73, 0x73, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1f, 0x2e, 0x73,
	0x79, 0x6e, 0x63, 0x61, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x6f, 0x73, 0x73, 0x2e, 0x41, 0x6c, 0x69,
	0x79, 0x75, 0x6e, 0x4f, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x73, 0x79, 0x6e, 0x63, 0x61, 0x6c, 0x69, 0x79, 0x75, 0x6e, 0x6f, 0x73, 0x73, 0x2e, 0x41, 0x6c,
	0x69, 0x79, 0x75, 0x6e, 0x4f, 0x73, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_syncaliyunoss_proto_rawDescOnce sync.Once
	file_syncaliyunoss_proto_rawDescData = file_syncaliyunoss_proto_rawDesc
)

func file_syncaliyunoss_proto_rawDescGZIP() []byte {
	file_syncaliyunoss_proto_rawDescOnce.Do(func() {
		file_syncaliyunoss_proto_rawDescData = protoimpl.X.CompressGZIP(file_syncaliyunoss_proto_rawDescData)
	})
	return file_syncaliyunoss_proto_rawDescData
}

var file_syncaliyunoss_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_syncaliyunoss_proto_goTypes = []interface{}{
	(*AliyunOssRequest)(nil), // 0: syncaliyunoss.AliyunOssRequest
	(*AliyunOssReply)(nil),   // 1: syncaliyunoss.AliyunOssReply
}
var file_syncaliyunoss_proto_depIdxs = []int32{
	0, // 0: syncaliyunoss.SyncAliyunOssFile.SyncOssFile:input_type -> syncaliyunoss.AliyunOssRequest
	1, // 1: syncaliyunoss.SyncAliyunOssFile.SyncOssFile:output_type -> syncaliyunoss.AliyunOssReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_syncaliyunoss_proto_init() }
func file_syncaliyunoss_proto_init() {
	if File_syncaliyunoss_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_syncaliyunoss_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AliyunOssRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_syncaliyunoss_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AliyunOssReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_syncaliyunoss_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_syncaliyunoss_proto_goTypes,
		DependencyIndexes: file_syncaliyunoss_proto_depIdxs,
		MessageInfos:      file_syncaliyunoss_proto_msgTypes,
	}.Build()
	File_syncaliyunoss_proto = out.File
	file_syncaliyunoss_proto_rawDesc = nil
	file_syncaliyunoss_proto_goTypes = nil
	file_syncaliyunoss_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SyncAliyunOssFileClient is the client API for SyncAliyunOssFile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SyncAliyunOssFileClient interface {
	SyncOssFile(ctx context.Context, in *AliyunOssRequest, opts ...grpc.CallOption) (*AliyunOssReply, error)
}

type syncAliyunOssFileClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncAliyunOssFileClient(cc grpc.ClientConnInterface) SyncAliyunOssFileClient {
	return &syncAliyunOssFileClient{cc}
}

func (c *syncAliyunOssFileClient) SyncOssFile(ctx context.Context, in *AliyunOssRequest, opts ...grpc.CallOption) (*AliyunOssReply, error) {
	out := new(AliyunOssReply)
	err := c.cc.Invoke(ctx, "/syncaliyunoss.SyncAliyunOssFile/SyncOssFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SyncAliyunOssFileServer is the server API for SyncAliyunOssFile service.
type SyncAliyunOssFileServer interface {
	SyncOssFile(context.Context, *AliyunOssRequest) (*AliyunOssReply, error)
}

// UnimplementedSyncAliyunOssFileServer can be embedded to have forward compatible implementations.
type UnimplementedSyncAliyunOssFileServer struct {
}

func (*UnimplementedSyncAliyunOssFileServer) SyncOssFile(context.Context, *AliyunOssRequest) (*AliyunOssReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncOssFile not implemented")
}

func RegisterSyncAliyunOssFileServer(s *grpc.Server, srv SyncAliyunOssFileServer) {
	s.RegisterService(&_SyncAliyunOssFile_serviceDesc, srv)
}

func _SyncAliyunOssFile_SyncOssFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliyunOssRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncAliyunOssFileServer).SyncOssFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/syncaliyunoss.SyncAliyunOssFile/SyncOssFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncAliyunOssFileServer).SyncOssFile(ctx, req.(*AliyunOssRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SyncAliyunOssFile_serviceDesc = grpc.ServiceDesc{
	ServiceName: "syncaliyunoss.SyncAliyunOssFile",
	HandlerType: (*SyncAliyunOssFileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncOssFile",
			Handler:    _SyncAliyunOssFile_SyncOssFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "syncaliyunoss.proto",
}
